// Code generated by MockGen. DO NOT EDIT.
// Source: auth_service/internal/delivery/http/auth_handler.go

// Package mock is a generated GoMock package.
package mock

import (
	transport "apple_backend/auth_service/internal/delivery/transport"
	domain "apple_backend/auth_service/internal/domain"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAuthUseCaseInterface is a mock of AuthUseCaseInterface interface.
type MockAuthUseCaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAuthUseCaseInterfaceMockRecorder
}

// MockAuthUseCaseInterfaceMockRecorder is the mock recorder for MockAuthUseCaseInterface.
type MockAuthUseCaseInterfaceMockRecorder struct {
	mock *MockAuthUseCaseInterface
}

// NewMockAuthUseCaseInterface creates a new mock instance.
func NewMockAuthUseCaseInterface(ctrl *gomock.Controller) *MockAuthUseCaseInterface {
	mock := &MockAuthUseCaseInterface{ctrl: ctrl}
	mock.recorder = &MockAuthUseCaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthUseCaseInterface) EXPECT() *MockAuthUseCaseInterfaceMockRecorder {
	return m.recorder
}

// GetUserByID mocks base method.
func (m *MockAuthUseCaseInterface) GetUserByID(ctx context.Context, userID string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, userID)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockAuthUseCaseInterfaceMockRecorder) GetUserByID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockAuthUseCaseInterface)(nil).GetUserByID), ctx, userID)
}

// Login mocks base method.
func (m *MockAuthUseCaseInterface) Login(ctx context.Context, email, password string) (*transport.AuthResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, email, password)
	ret0, _ := ret[0].(*transport.AuthResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthUseCaseInterfaceMockRecorder) Login(ctx, email, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthUseCaseInterface)(nil).Login), ctx, email, password)
}

// RefreshToken mocks base method.
func (m *MockAuthUseCaseInterface) RefreshToken(ctx context.Context, tokenString string) (*transport.AuthResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", ctx, tokenString)
	ret0, _ := ret[0].(*transport.AuthResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockAuthUseCaseInterfaceMockRecorder) RefreshToken(ctx, tokenString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockAuthUseCaseInterface)(nil).RefreshToken), ctx, tokenString)
}

// Register mocks base method.
func (m *MockAuthUseCaseInterface) Register(ctx context.Context, email, password string) (*transport.AuthResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, email, password)
	ret0, _ := ret[0].(*transport.AuthResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockAuthUseCaseInterfaceMockRecorder) Register(ctx, email, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAuthUseCaseInterface)(nil).Register), ctx, email, password)
}

// ValidateEmail mocks base method.
func (m *MockAuthUseCaseInterface) ValidateEmail(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateEmail", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateEmail indicates an expected call of ValidateEmail.
func (mr *MockAuthUseCaseInterfaceMockRecorder) ValidateEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateEmail", reflect.TypeOf((*MockAuthUseCaseInterface)(nil).ValidateEmail), ctx, email)
}

// VerifyToken mocks base method.
func (m *MockAuthUseCaseInterface) VerifyToken(ctx context.Context, tokenString string) (*transport.Claims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyToken", ctx, tokenString)
	ret0, _ := ret[0].(*transport.Claims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyToken indicates an expected call of VerifyToken.
func (mr *MockAuthUseCaseInterfaceMockRecorder) VerifyToken(ctx, tokenString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyToken", reflect.TypeOf((*MockAuthUseCaseInterface)(nil).VerifyToken), ctx, tokenString)
}
