// Code generated by MockGen. DO NOT EDIT.
// Source: ./profile_service/internal/delivery/http/avatar_handler.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	io "io"
	multipart "mime/multipart"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAvatarUsecaseInterface is a mock of AvatarUsecaseInterface interface.
type MockAvatarUsecaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarUsecaseInterfaceMockRecorder
}

// MockAvatarUsecaseInterfaceMockRecorder is the mock recorder for MockAvatarUsecaseInterface.
type MockAvatarUsecaseInterfaceMockRecorder struct {
	mock *MockAvatarUsecaseInterface
}

// NewMockAvatarUsecaseInterface creates a new mock instance.
func NewMockAvatarUsecaseInterface(ctrl *gomock.Controller) *MockAvatarUsecaseInterface {
	mock := &MockAvatarUsecaseInterface{ctrl: ctrl}
	mock.recorder = &MockAvatarUsecaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarUsecaseInterface) EXPECT() *MockAvatarUsecaseInterfaceMockRecorder {
	return m.recorder
}

// UploadAvatar mocks base method.
func (m *MockAvatarUsecaseInterface) UploadAvatar(ctx context.Context, userID string, file io.Reader, fileHeader *multipart.FileHeader) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadAvatar", ctx, userID, file, fileHeader)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadAvatar indicates an expected call of UploadAvatar.
func (mr *MockAvatarUsecaseInterfaceMockRecorder) UploadAvatar(ctx, userID, file, fileHeader interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadAvatar", reflect.TypeOf((*MockAvatarUsecaseInterface)(nil).UploadAvatar), ctx, userID, file, fileHeader)
}
