// Code generated by MockGen. DO NOT EDIT.
// Source: profile_handler.go

// Package mock is a generated GoMock package.
package mock

import (
	domain "apple_backend/profile_service/internal/domain"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockProfileUsecaseInterface is a mock of ProfileUsecaseInterface interface.
type MockProfileUsecaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockProfileUsecaseInterfaceMockRecorder
}

// MockProfileUsecaseInterfaceMockRecorder is the mock recorder for MockProfileUsecaseInterface.
type MockProfileUsecaseInterfaceMockRecorder struct {
	mock *MockProfileUsecaseInterface
}

// NewMockProfileUsecaseInterface creates a new mock instance.
func NewMockProfileUsecaseInterface(ctrl *gomock.Controller) *MockProfileUsecaseInterface {
	mock := &MockProfileUsecaseInterface{ctrl: ctrl}
	mock.recorder = &MockProfileUsecaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileUsecaseInterface) EXPECT() *MockProfileUsecaseInterfaceMockRecorder {
	return m.recorder
}

// CreateProfile mocks base method.
func (m *MockProfileUsecaseInterface) CreateProfile(ctx context.Context, email, passwordHash string) (*domain.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProfile", ctx, email, passwordHash)
	ret0, _ := ret[0].(*domain.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProfile indicates an expected call of CreateProfile.
func (mr *MockProfileUsecaseInterfaceMockRecorder) CreateProfile(ctx, email, passwordHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProfile", reflect.TypeOf((*MockProfileUsecaseInterface)(nil).CreateProfile), ctx, email, passwordHash)
}

// DeleteProfile mocks base method.
func (m *MockProfileUsecaseInterface) DeleteProfile(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProfile", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProfile indicates an expected call of DeleteProfile.
func (mr *MockProfileUsecaseInterfaceMockRecorder) DeleteProfile(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProfile", reflect.TypeOf((*MockProfileUsecaseInterface)(nil).DeleteProfile), ctx, id)
}

// GetProfile mocks base method.
func (m *MockProfileUsecaseInterface) GetProfile(ctx context.Context, id string) (*domain.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfile", ctx, id)
	ret0, _ := ret[0].(*domain.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfile indicates an expected call of GetProfile.
func (mr *MockProfileUsecaseInterfaceMockRecorder) GetProfile(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfile", reflect.TypeOf((*MockProfileUsecaseInterface)(nil).GetProfile), ctx, id)
}

// GetProfileByEmail mocks base method.
func (m *MockProfileUsecaseInterface) GetProfileByEmail(ctx context.Context, email string) (*domain.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfileByEmail", ctx, email)
	ret0, _ := ret[0].(*domain.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfileByEmail indicates an expected call of GetProfileByEmail.
func (mr *MockProfileUsecaseInterfaceMockRecorder) GetProfileByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfileByEmail", reflect.TypeOf((*MockProfileUsecaseInterface)(nil).GetProfileByEmail), ctx, email)
}

// UpdateProfile mocks base method.
func (m *MockProfileUsecaseInterface) UpdateProfile(ctx context.Context, profile *domain.Profile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", ctx, profile)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockProfileUsecaseInterfaceMockRecorder) UpdateProfile(ctx, profile interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockProfileUsecaseInterface)(nil).UpdateProfile), ctx, profile)
}
