// Code generated by MockGen. DO NOT EDIT.
// Source: store_service/internal/delivery/http/cart_handler.go

// Package mock is a generated GoMock package.
package mock

import (
	domain "apple_backend/store_service/internal/domain"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCartUsecaseInterface is a mock of CartUsecaseInterface interface.
type MockCartUsecaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCartUsecaseInterfaceMockRecorder
}

// MockCartUsecaseInterfaceMockRecorder is the mock recorder for MockCartUsecaseInterface.
type MockCartUsecaseInterfaceMockRecorder struct {
	mock *MockCartUsecaseInterface
}

// NewMockCartUsecaseInterface creates a new mock instance.
func NewMockCartUsecaseInterface(ctrl *gomock.Controller) *MockCartUsecaseInterface {
	mock := &MockCartUsecaseInterface{ctrl: ctrl}
	mock.recorder = &MockCartUsecaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCartUsecaseInterface) EXPECT() *MockCartUsecaseInterfaceMockRecorder {
	return m.recorder
}

// GetCart mocks base method.
func (m *MockCartUsecaseInterface) GetCart(ctx context.Context, userID string) (*domain.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCart", ctx, userID)
	ret0, _ := ret[0].(*domain.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCart indicates an expected call of GetCart.
func (mr *MockCartUsecaseInterfaceMockRecorder) GetCart(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCart", reflect.TypeOf((*MockCartUsecaseInterface)(nil).GetCart), ctx, userID)
}

// UpdateCart mocks base method.
func (m *MockCartUsecaseInterface) UpdateCart(ctx context.Context, cartID string, updateCart *domain.CartUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCart", ctx, cartID, updateCart)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCart indicates an expected call of UpdateCart.
func (mr *MockCartUsecaseInterfaceMockRecorder) UpdateCart(ctx, cartID, updateCart interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCart", reflect.TypeOf((*MockCartUsecaseInterface)(nil).UpdateCart), ctx, cartID, updateCart)
}
