// Code generated by MockGen. DO NOT EDIT.
// Source: store_service/internal/delivery/http/store_handler.go

// Package mock is a generated GoMock package.
package mock

import (
	domain "apple_backend/store_service/internal/domain"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockStoreUsecaseInterface is a mock of StoreUsecaseInterface interface.
type MockStoreUsecaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockStoreUsecaseInterfaceMockRecorder
}

// MockStoreUsecaseInterfaceMockRecorder is the mock recorder for MockStoreUsecaseInterface.
type MockStoreUsecaseInterfaceMockRecorder struct {
	mock *MockStoreUsecaseInterface
}

// NewMockStoreUsecaseInterface creates a new mock instance.
func NewMockStoreUsecaseInterface(ctrl *gomock.Controller) *MockStoreUsecaseInterface {
	mock := &MockStoreUsecaseInterface{ctrl: ctrl}
	mock.recorder = &MockStoreUsecaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoreUsecaseInterface) EXPECT() *MockStoreUsecaseInterfaceMockRecorder {
	return m.recorder
}

// CreateStore mocks base method.
func (m *MockStoreUsecaseInterface) CreateStore(ctx context.Context, name, description, cityID, address, cardImg, openAt, closedAt string, rating float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStore", ctx, name, description, cityID, address, cardImg, openAt, closedAt, rating)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateStore indicates an expected call of CreateStore.
func (mr *MockStoreUsecaseInterfaceMockRecorder) CreateStore(ctx, name, description, cityID, address, cardImg, openAt, closedAt, rating interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStore", reflect.TypeOf((*MockStoreUsecaseInterface)(nil).CreateStore), ctx, name, description, cityID, address, cardImg, openAt, closedAt, rating)
}

// GetCities mocks base method.
func (m *MockStoreUsecaseInterface) GetCities(ctx context.Context) ([]*domain.City, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCities", ctx)
	ret0, _ := ret[0].([]*domain.City)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCities indicates an expected call of GetCities.
func (mr *MockStoreUsecaseInterfaceMockRecorder) GetCities(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCities", reflect.TypeOf((*MockStoreUsecaseInterface)(nil).GetCities), ctx)
}

// GetStore mocks base method.
func (m *MockStoreUsecaseInterface) GetStore(ctx context.Context, id string) (*domain.Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStore", ctx, id)
	ret0, _ := ret[0].(*domain.Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStore indicates an expected call of GetStore.
func (mr *MockStoreUsecaseInterfaceMockRecorder) GetStore(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStore", reflect.TypeOf((*MockStoreUsecaseInterface)(nil).GetStore), ctx, id)
}

// GetStoreReview mocks base method.
func (m *MockStoreUsecaseInterface) GetStoreReview(ctx context.Context, id string) ([]*domain.StoreReview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStoreReview", ctx, id)
	ret0, _ := ret[0].([]*domain.StoreReview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStoreReview indicates an expected call of GetStoreReview.
func (mr *MockStoreUsecaseInterfaceMockRecorder) GetStoreReview(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStoreReview", reflect.TypeOf((*MockStoreUsecaseInterface)(nil).GetStoreReview), ctx, id)
}

// GetStores mocks base method.
func (m *MockStoreUsecaseInterface) GetStores(ctx context.Context, filter *domain.StoreFilter) ([]*domain.Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStores", ctx, filter)
	ret0, _ := ret[0].([]*domain.Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStores indicates an expected call of GetStores.
func (mr *MockStoreUsecaseInterfaceMockRecorder) GetStores(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStores", reflect.TypeOf((*MockStoreUsecaseInterface)(nil).GetStores), ctx, filter)
}

// GetTags mocks base method.
func (m *MockStoreUsecaseInterface) GetTags(ctx context.Context) ([]*domain.StoreTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTags", ctx)
	ret0, _ := ret[0].([]*domain.StoreTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTags indicates an expected call of GetTags.
func (mr *MockStoreUsecaseInterfaceMockRecorder) GetTags(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTags", reflect.TypeOf((*MockStoreUsecaseInterface)(nil).GetTags), ctx)
}
