// Code generated by MockGen. DO NOT EDIT.
// Source: store_service/internal/delivery/http/order_handler.go

// Package mock is a generated GoMock package.
package mock

import (
	domain "apple_backend/store_service/internal/domain"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockOrderUsecaseInterface is a mock of OrderUsecaseInterface interface.
type MockOrderUsecaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOrderUsecaseInterfaceMockRecorder
}

// MockOrderUsecaseInterfaceMockRecorder is the mock recorder for MockOrderUsecaseInterface.
type MockOrderUsecaseInterfaceMockRecorder struct {
	mock *MockOrderUsecaseInterface
}

// NewMockOrderUsecaseInterface creates a new mock instance.
func NewMockOrderUsecaseInterface(ctrl *gomock.Controller) *MockOrderUsecaseInterface {
	mock := &MockOrderUsecaseInterface{ctrl: ctrl}
	mock.recorder = &MockOrderUsecaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderUsecaseInterface) EXPECT() *MockOrderUsecaseInterfaceMockRecorder {
	return m.recorder
}

// CreateOrder mocks base method.
func (m *MockOrderUsecaseInterface) CreateOrder(ctx context.Context, userID string) (*domain.OrderInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", ctx, userID)
	ret0, _ := ret[0].(*domain.OrderInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockOrderUsecaseInterfaceMockRecorder) CreateOrder(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockOrderUsecaseInterface)(nil).CreateOrder), ctx, userID)
}

// GetOrder mocks base method.
func (m *MockOrderUsecaseInterface) GetOrder(ctx context.Context, id string) (*domain.OrderInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrder", ctx, id)
	ret0, _ := ret[0].(*domain.OrderInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrder indicates an expected call of GetOrder.
func (mr *MockOrderUsecaseInterfaceMockRecorder) GetOrder(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrder", reflect.TypeOf((*MockOrderUsecaseInterface)(nil).GetOrder), ctx, id)
}

// GetOrdersUser mocks base method.
func (m *MockOrderUsecaseInterface) GetOrdersUser(ctx context.Context, userID string) ([]*domain.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrdersUser", ctx, userID)
	ret0, _ := ret[0].([]*domain.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrdersUser indicates an expected call of GetOrdersUser.
func (mr *MockOrderUsecaseInterfaceMockRecorder) GetOrdersUser(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrdersUser", reflect.TypeOf((*MockOrderUsecaseInterface)(nil).GetOrdersUser), ctx, userID)
}

// UpdateOrderStatus mocks base method.
func (m *MockOrderUsecaseInterface) UpdateOrderStatus(ctx context.Context, orderID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatus", ctx, orderID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderStatus indicates an expected call of UpdateOrderStatus.
func (mr *MockOrderUsecaseInterfaceMockRecorder) UpdateOrderStatus(ctx, orderID, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatus", reflect.TypeOf((*MockOrderUsecaseInterface)(nil).UpdateOrderStatus), ctx, orderID, status)
}
