// Code generated by MockGen. DO NOT EDIT.
// Source: store_service/internal/delivery/http/item_handler.go

// Package mock is a generated GoMock package.
package mock

import (
	domain "apple_backend/store_service/internal/domain"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockItemUsecaseInterface is a mock of ItemUsecaseInterface interface.
type MockItemUsecaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockItemUsecaseInterfaceMockRecorder
}

// MockItemUsecaseInterfaceMockRecorder is the mock recorder for MockItemUsecaseInterface.
type MockItemUsecaseInterfaceMockRecorder struct {
	mock *MockItemUsecaseInterface
}

// NewMockItemUsecaseInterface creates a new mock instance.
func NewMockItemUsecaseInterface(ctrl *gomock.Controller) *MockItemUsecaseInterface {
	mock := &MockItemUsecaseInterface{ctrl: ctrl}
	mock.recorder = &MockItemUsecaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockItemUsecaseInterface) EXPECT() *MockItemUsecaseInterfaceMockRecorder {
	return m.recorder
}

// GetItemTypes mocks base method.
func (m *MockItemUsecaseInterface) GetItemTypes(ctx context.Context, id string) ([]*domain.ItemType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemTypes", ctx, id)
	ret0, _ := ret[0].([]*domain.ItemType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItemTypes indicates an expected call of GetItemTypes.
func (mr *MockItemUsecaseInterfaceMockRecorder) GetItemTypes(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemTypes", reflect.TypeOf((*MockItemUsecaseInterface)(nil).GetItemTypes), ctx, id)
}

// GetItems mocks base method.
func (m *MockItemUsecaseInterface) GetItems(ctx context.Context, id string) ([]*domain.ItemAgg, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItems", ctx, id)
	ret0, _ := ret[0].([]*domain.ItemAgg)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItems indicates an expected call of GetItems.
func (mr *MockItemUsecaseInterfaceMockRecorder) GetItems(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItems", reflect.TypeOf((*MockItemUsecaseInterface)(nil).GetItems), ctx, id)
}
