// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: pkg/proto/embedding/embedding.proto

package embeddingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetEmbeddingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmbeddingRequest) Reset() {
	*x = GetEmbeddingRequest{}
	mi := &file_pkg_proto_embedding_embedding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmbeddingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmbeddingRequest) ProtoMessage() {}

func (x *GetEmbeddingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_embedding_embedding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmbeddingRequest.ProtoReflect.Descriptor instead.
func (*GetEmbeddingRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_embedding_embedding_proto_rawDescGZIP(), []int{0}
}

func (x *GetEmbeddingRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type GetEmbeddingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embedding     []float32              `protobuf:"fixed32,1,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Dimensions    int32                  `protobuf:"varint,3,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmbeddingResponse) Reset() {
	*x = GetEmbeddingResponse{}
	mi := &file_pkg_proto_embedding_embedding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmbeddingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmbeddingResponse) ProtoMessage() {}

func (x *GetEmbeddingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_embedding_embedding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmbeddingResponse.ProtoReflect.Descriptor instead.
func (*GetEmbeddingResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_embedding_embedding_proto_rawDescGZIP(), []int{1}
}

func (x *GetEmbeddingResponse) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *GetEmbeddingResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GetEmbeddingResponse) GetDimensions() int32 {
	if x != nil {
		return x.Dimensions
	}
	return 0
}

type GetEmbeddingBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Texts         []string               `protobuf:"bytes,1,rep,name=texts,proto3" json:"texts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmbeddingBatchRequest) Reset() {
	*x = GetEmbeddingBatchRequest{}
	mi := &file_pkg_proto_embedding_embedding_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmbeddingBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmbeddingBatchRequest) ProtoMessage() {}

func (x *GetEmbeddingBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_embedding_embedding_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmbeddingBatchRequest.ProtoReflect.Descriptor instead.
func (*GetEmbeddingBatchRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_embedding_embedding_proto_rawDescGZIP(), []int{2}
}

func (x *GetEmbeddingBatchRequest) GetTexts() []string {
	if x != nil {
		return x.Texts
	}
	return nil
}

type GetEmbeddingBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*EmbeddingResult     `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmbeddingBatchResponse) Reset() {
	*x = GetEmbeddingBatchResponse{}
	mi := &file_pkg_proto_embedding_embedding_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmbeddingBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmbeddingBatchResponse) ProtoMessage() {}

func (x *GetEmbeddingBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_embedding_embedding_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmbeddingBatchResponse.ProtoReflect.Descriptor instead.
func (*GetEmbeddingBatchResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_embedding_embedding_proto_rawDescGZIP(), []int{3}
}

func (x *GetEmbeddingBatchResponse) GetResults() []*EmbeddingResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type EmbeddingResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Embedding     []float32              `protobuf:"fixed32,2,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingResult) Reset() {
	*x = EmbeddingResult{}
	mi := &file_pkg_proto_embedding_embedding_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingResult) ProtoMessage() {}

func (x *EmbeddingResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_embedding_embedding_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingResult.ProtoReflect.Descriptor instead.
func (*EmbeddingResult) Descriptor() ([]byte, []int) {
	return file_pkg_proto_embedding_embedding_proto_rawDescGZIP(), []int{4}
}

func (x *EmbeddingResult) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *EmbeddingResult) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_pkg_proto_embedding_embedding_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_embedding_embedding_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_embedding_embedding_proto_rawDescGZIP(), []int{5}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_pkg_proto_embedding_embedding_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_embedding_embedding_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_embedding_embedding_proto_rawDescGZIP(), []int{6}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_proto_embedding_embedding_proto protoreflect.FileDescriptor

const file_pkg_proto_embedding_embedding_proto_rawDesc = "" +
	"\n" +
	"#pkg/proto/embedding/embedding.proto\x12\fembedding.v1\")\n" +
	"\x13GetEmbeddingRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"j\n" +
	"\x14GetEmbeddingResponse\x12\x1c\n" +
	"\tembedding\x18\x01 \x03(\x02R\tembedding\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x1e\n" +
	"\n" +
	"dimensions\x18\x03 \x01(\x05R\n" +
	"dimensions\"0\n" +
	"\x18GetEmbeddingBatchRequest\x12\x14\n" +
	"\x05texts\x18\x01 \x03(\tR\x05texts\"T\n" +
	"\x19GetEmbeddingBatchResponse\x127\n" +
	"\aresults\x18\x01 \x03(\v2\x1d.embedding.v1.EmbeddingResultR\aresults\"C\n" +
	"\x0fEmbeddingResult\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1c\n" +
	"\tembedding\x18\x02 \x03(\x02R\tembedding\"\x0f\n" +
	"\rHealthRequest\"D\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x94\x02\n" +
	"\x10EmbeddingService\x12U\n" +
	"\fGetEmbedding\x12!.embedding.v1.GetEmbeddingRequest\x1a\".embedding.v1.GetEmbeddingResponse\x12d\n" +
	"\x11GetEmbeddingBatch\x12&.embedding.v1.GetEmbeddingBatchRequest\x1a'.embedding.v1.GetEmbeddingBatchResponse\x12C\n" +
	"\x06Health\x12\x1b.embedding.v1.HealthRequest\x1a\x1c.embedding.v1.HealthResponseB!Z\x1fpkg/proto/embedding;embeddingv1b\x06proto3"

var (
	file_pkg_proto_embedding_embedding_proto_rawDescOnce sync.Once
	file_pkg_proto_embedding_embedding_proto_rawDescData []byte
)

func file_pkg_proto_embedding_embedding_proto_rawDescGZIP() []byte {
	file_pkg_proto_embedding_embedding_proto_rawDescOnce.Do(func() {
		file_pkg_proto_embedding_embedding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_embedding_embedding_proto_rawDesc), len(file_pkg_proto_embedding_embedding_proto_rawDesc)))
	})
	return file_pkg_proto_embedding_embedding_proto_rawDescData
}

var file_pkg_proto_embedding_embedding_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_proto_embedding_embedding_proto_goTypes = []any{
	(*GetEmbeddingRequest)(nil),       // 0: embedding.v1.GetEmbeddingRequest
	(*GetEmbeddingResponse)(nil),      // 1: embedding.v1.GetEmbeddingResponse
	(*GetEmbeddingBatchRequest)(nil),  // 2: embedding.v1.GetEmbeddingBatchRequest
	(*GetEmbeddingBatchResponse)(nil), // 3: embedding.v1.GetEmbeddingBatchResponse
	(*EmbeddingResult)(nil),           // 4: embedding.v1.EmbeddingResult
	(*HealthRequest)(nil),             // 5: embedding.v1.HealthRequest
	(*HealthResponse)(nil),            // 6: embedding.v1.HealthResponse
}
var file_pkg_proto_embedding_embedding_proto_depIdxs = []int32{
	4, // 0: embedding.v1.GetEmbeddingBatchResponse.results:type_name -> embedding.v1.EmbeddingResult
	0, // 1: embedding.v1.EmbeddingService.GetEmbedding:input_type -> embedding.v1.GetEmbeddingRequest
	2, // 2: embedding.v1.EmbeddingService.GetEmbeddingBatch:input_type -> embedding.v1.GetEmbeddingBatchRequest
	5, // 3: embedding.v1.EmbeddingService.Health:input_type -> embedding.v1.HealthRequest
	1, // 4: embedding.v1.EmbeddingService.GetEmbedding:output_type -> embedding.v1.GetEmbeddingResponse
	3, // 5: embedding.v1.EmbeddingService.GetEmbeddingBatch:output_type -> embedding.v1.GetEmbeddingBatchResponse
	6, // 6: embedding.v1.EmbeddingService.Health:output_type -> embedding.v1.HealthResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_embedding_embedding_proto_init() }
func file_pkg_proto_embedding_embedding_proto_init() {
	if File_pkg_proto_embedding_embedding_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_embedding_embedding_proto_rawDesc), len(file_pkg_proto_embedding_embedding_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_embedding_embedding_proto_goTypes,
		DependencyIndexes: file_pkg_proto_embedding_embedding_proto_depIdxs,
		MessageInfos:      file_pkg_proto_embedding_embedding_proto_msgTypes,
	}.Build()
	File_pkg_proto_embedding_embedding_proto = out.File
	file_pkg_proto_embedding_embedding_proto_goTypes = nil
	file_pkg_proto_embedding_embedding_proto_depIdxs = nil
}
