// Code generated by MockGen. DO NOT EDIT.
// Source: store_service/internal/usecase/cart_usecase.go

// Package mock is a generated GoMock package.
package mock

import (
	domain "apple_backend/store_service/internal/domain"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCartRepository is a mock of CartRepository interface.
type MockCartRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCartRepositoryMockRecorder
}

// MockCartRepositoryMockRecorder is the mock recorder for MockCartRepository.
type MockCartRepositoryMockRecorder struct {
	mock *MockCartRepository
}

// NewMockCartRepository creates a new mock instance.
func NewMockCartRepository(ctrl *gomock.Controller) *MockCartRepository {
	mock := &MockCartRepository{ctrl: ctrl}
	mock.recorder = &MockCartRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCartRepository) EXPECT() *MockCartRepositoryMockRecorder {
	return m.recorder
}

// DeleteCartItems mocks base method.
func (m *MockCartRepository) DeleteCartItems(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCartItems", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCartItems indicates an expected call of DeleteCartItems.
func (mr *MockCartRepositoryMockRecorder) DeleteCartItems(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCartItems", reflect.TypeOf((*MockCartRepository)(nil).DeleteCartItems), ctx, id)
}

// GetCartItems mocks base method.
func (m *MockCartRepository) GetCartItems(ctx context.Context, userID string) (string, []*domain.CartItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCartItems", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]*domain.CartItem)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetCartItems indicates an expected call of GetCartItems.
func (mr *MockCartRepositoryMockRecorder) GetCartItems(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCartItems", reflect.TypeOf((*MockCartRepository)(nil).GetCartItems), ctx, userID)
}

// UpdateCartItems mocks base method.
func (m *MockCartRepository) UpdateCartItems(ctx context.Context, id string, newItems *domain.CartUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCartItems", ctx, id, newItems)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCartItems indicates an expected call of UpdateCartItems.
func (mr *MockCartRepositoryMockRecorder) UpdateCartItems(ctx, id, newItems interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCartItems", reflect.TypeOf((*MockCartRepository)(nil).UpdateCartItems), ctx, id, newItems)
}
