// Code generated by MockGen. DO NOT EDIT.
// Source: store_service/internal/usecase/store_usecase.go

// Package mock is a generated GoMock package.
package mock

import (
	domain "apple_backend/store_service/internal/domain"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockStoreRepository is a mock of StoreRepository interface.
type MockStoreRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStoreRepositoryMockRecorder
}

// MockStoreRepositoryMockRecorder is the mock recorder for MockStoreRepository.
type MockStoreRepositoryMockRecorder struct {
	mock *MockStoreRepository
}

// NewMockStoreRepository creates a new mock instance.
func NewMockStoreRepository(ctrl *gomock.Controller) *MockStoreRepository {
	mock := &MockStoreRepository{ctrl: ctrl}
	mock.recorder = &MockStoreRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoreRepository) EXPECT() *MockStoreRepositoryMockRecorder {
	return m.recorder
}

// CreateStore mocks base method.
func (m *MockStoreRepository) CreateStore(ctx context.Context, store *domain.Store) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStore", ctx, store)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateStore indicates an expected call of CreateStore.
func (mr *MockStoreRepositoryMockRecorder) CreateStore(ctx, store interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStore", reflect.TypeOf((*MockStoreRepository)(nil).CreateStore), ctx, store)
}

// GetCities mocks base method.
func (m *MockStoreRepository) GetCities(ctx context.Context) ([]*domain.City, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCities", ctx)
	ret0, _ := ret[0].([]*domain.City)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCities indicates an expected call of GetCities.
func (mr *MockStoreRepositoryMockRecorder) GetCities(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCities", reflect.TypeOf((*MockStoreRepository)(nil).GetCities), ctx)
}

// GetStore mocks base method.
func (m *MockStoreRepository) GetStore(ctx context.Context, id string) ([]*domain.Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStore", ctx, id)
	ret0, _ := ret[0].([]*domain.Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStore indicates an expected call of GetStore.
func (mr *MockStoreRepositoryMockRecorder) GetStore(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStore", reflect.TypeOf((*MockStoreRepository)(nil).GetStore), ctx, id)
}

// GetStoreReview mocks base method.
func (m *MockStoreRepository) GetStoreReview(ctx context.Context, id string) ([]*domain.StoreReview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStoreReview", ctx, id)
	ret0, _ := ret[0].([]*domain.StoreReview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStoreReview indicates an expected call of GetStoreReview.
func (mr *MockStoreRepositoryMockRecorder) GetStoreReview(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStoreReview", reflect.TypeOf((*MockStoreRepository)(nil).GetStoreReview), ctx, id)
}

// GetStores mocks base method.
func (m *MockStoreRepository) GetStores(ctx context.Context, filter *domain.StoreFilter) ([]*domain.Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStores", ctx, filter)
	ret0, _ := ret[0].([]*domain.Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStores indicates an expected call of GetStores.
func (mr *MockStoreRepositoryMockRecorder) GetStores(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStores", reflect.TypeOf((*MockStoreRepository)(nil).GetStores), ctx, filter)
}

// GetTags mocks base method.
func (m *MockStoreRepository) GetTags(ctx context.Context) ([]*domain.StoreTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTags", ctx)
	ret0, _ := ret[0].([]*domain.StoreTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTags indicates an expected call of GetTags.
func (mr *MockStoreRepositoryMockRecorder) GetTags(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTags", reflect.TypeOf((*MockStoreRepository)(nil).GetTags), ctx)
}
